-- This is a demo on IDENTITY column in SAP HANA

-- Create a table without the IDENTITY column at the begginning
CREATE COLUMN TABLE KAFKA_TEST_ID(
	NAME VARCHAR(32),
	TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- insert two records
insert into "AXU"."KAFKA_TEST_ID"(name) values('Alex')#
insert into "AXU"."KAFKA_TEST_ID"(name) values('Bob')#

-- check result
select * from "AXU"."KAFKA_TEST_ID"

NAME;TS
Alex;Aug 12, 2019 4:04:55.385 PM
Bob;Aug 12, 2019 4:04:55.482 PM

-- add ID column
ALTER TABLE "AXU"."KAFKA_TEST_ID" ADD (
	KAFKA_ID integer generated by default as IDENTITY
);

-- check result, now we have a column KAFKA_ID, the above two records also have been assgined values:
NAME;TS;KAFKA_ID
Alex;Aug 12, 2019 4:04:55.385 PM;1
Bob; Aug 12, 2019 4:04:55.482 PM;2

-- insert two more records
insert into "AXU"."KAFKA_TEST_ID"(name) values('Caleb')#
insert into "AXU"."KAFKA_TEST_ID"(name) values('David')#
-- check results
NAME;TS;KAFKA_ID
Alex;Aug 12, 2019 4:04:55.385 PM;1
Bob;Aug 12, 2019 4:04:55.482 PM;2
Caleb;Aug 12, 2019 4:08:22.393 PM;3
David;Aug 12, 2019 4:08:22.49 PM;4

/*
Note:
GENERATED BY DEFAULT AS IDENTITY vs GENERATED ALWAYS AS IDENTITY
*/


-- The magic behind IDENTITY column is still sequences
select column_name, column_id from table_columns where table_name ='KAFKA_TEST_ID'

COLUMN_NAME;COLUMN_ID
KAFKA_ID;682,937,944
NAME;682,920,253
TS;682,920,254

select * from sequences where sequence_name like '%682937944%'

SCHEMA_NAME;SEQUENCE_NAME;SEQUENCE_OID;START_NUMBER;MIN_VALUE;MAX_VALUE;INCREMENT_BY;IS_CYCLED;RESET_BY_QUERY;CACHE_SIZE;CREATE_TIME
AXU;_SYS_SEQUENCE_682937944_#0_#;682,937,945;1;1;9,223,372,036,854,775,807;1;FALSE;select ifnull(MAP( mod((max( to_decimal("KAFKA_ID")) - (1) ),1),  0, max("KAFKA_ID") +1,  max("KAFKA_ID") - mod((max( "KAFKA_ID") - (1)), 1 ) +1 ) , 1) from "AXU"."KAFKA_TEST_ID";1;Aug 12, 2019 4:06:29.996 PM

Now you know how ID column is created.
